#!/usr/bin/env bash


install() {
	[ -d "$CONF_DIR" ] || sudo mkdir "$CONF_DIR"
	[ -L "$CONF_PATH" ] || sudo ln -s "share/etc/$CONF_FILE" "$CONF_DIR"
	[ -d "$install_dir" ] || mkdir "$install_dir"

	[ -L "$EXEC_FILE" ] || sudo ln -s "src/engine.rb" "$EXEC_FILE" && chmod +x "$EXEC_FILE"

	for file in $SRC; do
		dst="$install_dir/${file}"

		[ -L "$dst" ] || ln -s "$(realpath "src/${file}")" "${install_dir}/"
	done
}

clean() {
	echo "${CONF_DIR} and ${install_dir} will not be deleted as part of the cleanup process"

	[ -L $CONF_PATH ] && sudo rm $CONF_PATH
	[ -d "$install_dir" ] && rm "${install_dir}"/*
}

CONF_DIR="/etc/one"
CONF_FILE="provision_engine.conf"
CONF_PATH="${CONF_DIR}/${CONF_FILE}"
EXEC_FILE="/usr/bin/opengine"

SRC="log.rb configuration.rb API/rest.rb CloudClient/client.rb CloudClient/faas.rb"

action="${1:-"install"}"
install_dir="${2:-"/opt/ProvisionEngine"}"

if [ "$action" = "clean" ]; then
	clean
else
	install
fi
