#!/usr/bin/env bash

PE="provision-engine"
PES="${PE}-server"
LOG_DIR="/var/log/${PE}"
LOG="${LOG_DIR}/api.log"
SERVER="/opt/${PE}/server.rb"
PID="/tmp/${PES}.pid"

start() {
	if [ -f $PID ]; then
		echo "Found pid $(cat $PID) at ${PID}" >&2
		echo "Provision Engine is already running or wasn't stopped cleanly" >&2
		exit 1
	fi

	[ "$1" == 'debug' ] && cmd="ruby -dw" || cmd="ruby"

	[ -d $LOG_DIR ] || sudo mkdir $LOG_DIR && sudo chown "$USER" $LOG_DIR

	# start server in background due to sinatra locking the prompt. Redirect sinatra output to logfile
	if $cmd $SERVER > $LOG 2>&1 & then
		echo "${PES} started"
		echo $! > $PID
	else
		echo "failed to start ${PES}. Check ${LOG}" >&2
		exit 1
	fi
}

stop() {
	if [ ! -f $PID ]; then
		echo "Could not find server pid file" >&2
		exit 1
	fi

	if kill -INT "$(cat $PID)"; then
		echo "${PES} stopped"
		rm -f $PID
	else
		echo "failed to stop ${PES}" >&2
	fi
}

help() {
	echo "Usage: ${PES} {start|stop} <debug>"
}

if [ "$1" == 'start' ]; then
	start "$2"
elif [ "$1" == 'stop' ]; then
	stop
else
	help
	exit 1
fi
