name: Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      ONE: "3.72.81.234" # opennebula endpoint to be used by the PE runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install
        run: ./install.sh

      - name: Configure
        run: cd ./tests && ./prepare.rb "http://${ONE}:2633/RPC2" "http://${ONE}:2474" 0 1

      # Maybe should be included in rspec
      - name: Start engine
        run: provision-engine-server start && sleep 2

      - name: Test
        run: cd ./tests && rspec tests.rb

      # Maybe should be included in rspec
      - name: Stop engine engine
        run: provision-engine-server stop

      - name: Uninstall
        run: ./install.sh purge
