name: Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      oned: https://cognit-lab.sovereignedge.eu/RPC2
      oneflow: https://cognit-lab-oneflow.sovereignedge.eu/
      nature: 2
      nature_s3: 4 # still not configured on the frontend nor it runs in the tests
      TESTS_AUTH: ${{ secrets.TESTS_AUTH }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install
        run: ./install.sh

      - name: Configure
        run: cd ./tests && ./prepare.rb "${{ env.oned }}" "${{ env.oneflow }}" "${{ env.nature }}" "${{ env.nature_s3 }}"

      # Maybe should be included in rspec
      - name: Start engine
        run: provision-engine-server start && sleep 2

      - name: Test
        run: cd ./tests && rspec tests.rb

      # Maybe should be included in rspec
      - name: Stop engine engine
        run: provision-engine-server stop

      - name: Uninstall
        run: ./install.sh purge
