name: Tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    env:
      oned: https://cognit-lab.sovereignedge.eu/RPC2
      oneflow: https://cognit-lab-oneflow.sovereignedge.eu/
      TESTS_AUTH: ${{ secrets.TESTS_AUTH }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install engine
        run: ./install.sh

      - name: Configure
        run: cd ./tests && ./prepare.rb "${{ env.oned }}" "${{ env.oneflow }}"

      - name: Start engine
        run: provision-engine-server start && sleep 2

      - name: Rspec
        run: cd ./tests && rspec init.rb

      - name: Stop engine
        run: provision-engine-server stop

      - name: Uninstall
        run: ./install.sh purge

